//! First-party ULID (Universally Unique Lexicographically Sortable Identifier).
//!
//! Replaces the `ulid` crate. Every id this store persists — the `NoteId` in an
//! object key, the `op_id` in a signed op-log entry, the version segment of a
//! blob key — is a ULID in the crate's canonical 26-character Crockford base32
//! form, so this port must stay byte-for-byte compatible with what already sits
//! in every bucket. The tests below pin it to vectors generated by `ulid 1.2.1`
//! itself before the crate was removed, including its lenient corners (either
//! letter case decodes; a leading digit above `7` silently drops its overflow
//! bits, exactly as the crate did).
//!
//! The crate's only production cost was its `rand 0.9` stack (`rand`,
//! `rand_chacha`, `rand_core 0.9` — a second copy beside schnorrkel's 0.8 line)
//! for the 80 random bits [`Ulid::new`] draws; those now come straight from the
//! OS CSPRNG.
//!
//! Layout (128 bits, big-endian): a 48-bit Unix timestamp in milliseconds, then
//! 80 random bits. Ordering is the plain `u128` order, so ids sort by creation
//! time first, and the base32 text sorts identically.

use core::fmt;
use core::str::FromStr;
use std::time::{SystemTime, UNIX_EPOCH};

use serde::{Deserialize, Serialize};

/// Length of the canonical text form.
pub const ULID_LEN: usize = 26;

const TIME_BITS: u32 = 48;
const RAND_BITS: u32 = 80;
const TIME_MASK: u64 = (1 << TIME_BITS) - 1;
const RAND_MASK: u128 = (1 << RAND_BITS) - 1;
/// Bytes of the 80-bit random part.
const RAND_BYTES: usize = 10;

/// Crockford base32: digits, then the letters minus `I`, `L`, `O`, `U`.
const ALPHABET: &[u8; 32] = b"0123456789ABCDEFGHJKMNPQRSTVWXYZ";
const NO_VALUE: u8 = 0xff;
/// Byte -> digit value, either letter case; `NO_VALUE` for anything else.
const LOOKUP: [u8; 256] = build_lookup();

#[expect(
    clippy::cast_possible_truncation,
    reason = "const table construction: `try_from` is not const-callable, and the index is < 32"
)]
const fn build_lookup() -> [u8; 256] {
    let mut table = [NO_VALUE; 256];
    let mut i = 0;
    while i < ALPHABET.len() {
        let upper = ALPHABET[i];
        table[upper as usize] = i as u8;
        table[upper.to_ascii_lowercase() as usize] = i as u8;
        i += 1;
    }
    table
}

/// A ULID. The payload is public, as it was in the `ulid` crate, so tests can
/// mint adjacent ids by arithmetic.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub struct Ulid(pub u128);

impl Ulid {
    /// Mint a fresh id from the current time and 80 bits of OS randomness.
    ///
    /// # Panics
    ///
    /// If the OS cannot supply randomness — the same catastrophic condition
    /// [`SecretKey::generate`](crate::crypto::SecretKey::generate) documents,
    /// which no caller can meaningfully handle. A clock before the Unix epoch
    /// yields timestamp 0 rather than a panic.
    #[must_use]
    #[expect(
        clippy::expect_used,
        reason = "OS CSPRNG failure is unrecoverable; documented under # Panics like the sibling key-generation path"
    )]
    #[expect(
        clippy::new_without_default,
        reason = "a Default impl would mint a random, clock-reading id; callers must opt in explicitly via new(), as with NoteId"
    )]
    pub fn new() -> Self {
        let millis = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map_or(0, |elapsed| {
                u64::try_from(elapsed.as_millis()).unwrap_or(u64::MAX)
            });

        let mut random = [0u8; 16];
        getrandom::fill(&mut random[16 - RAND_BYTES..]).expect("OS CSPRNG unavailable");

        Self::from_parts(millis, u128::from_be_bytes(random))
    }

    /// Assemble an id from its parts; overflow bits of either are discarded.
    #[must_use]
    pub fn from_parts(timestamp_ms: u64, random: u128) -> Self {
        Self((u128::from(timestamp_ms & TIME_MASK) << RAND_BITS) | (random & RAND_MASK))
    }

    /// The id whose big-endian encoding is `bytes`.
    #[must_use]
    pub const fn from_bytes(bytes: [u8; 16]) -> Self {
        Self(u128::from_be_bytes(bytes))
    }

    /// The big-endian encoding.
    #[must_use]
    pub const fn to_bytes(self) -> [u8; 16] {
        self.0.to_be_bytes()
    }

    /// Milliseconds since the Unix epoch, from the top 48 bits.
    #[must_use]
    pub fn timestamp_ms(self) -> u64 {
        // The shift leaves 48 bits, so this conversion is total.
        u64::try_from(self.0 >> RAND_BITS).unwrap_or(u64::MAX)
    }

    /// The 80-bit random part.
    #[must_use]
    pub const fn random(self) -> u128 {
        self.0 & RAND_MASK
    }

    /// Parse the canonical 26-character form (either letter case).
    ///
    /// # Errors
    ///
    /// [`DecodeError::InvalidLength`] unless exactly 26 bytes long,
    /// [`DecodeError::InvalidChar`] for a byte outside the Crockford alphabet.
    pub fn from_string(text: &str) -> Result<Self, DecodeError> {
        text.parse()
    }

    /// The canonical form as ASCII bytes, most significant digit first.
    fn encode(self) -> [u8; ULID_LEN] {
        let mut value = self.0;
        let mut out = [0u8; ULID_LEN];
        for slot in out.iter_mut().rev() {
            let digit = (value & 0x1f).to_le_bytes()[0];
            *slot = ALPHABET[usize::from(digit)];
            value >>= 5;
        }
        out
    }
}

impl From<u128> for Ulid {
    fn from(value: u128) -> Self {
        Self(value)
    }
}

impl From<Ulid> for u128 {
    fn from(ulid: Ulid) -> Self {
        ulid.0
    }
}

impl fmt::Display for Ulid {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let text = self.encode();
        // `ALPHABET` is ASCII, so the buffer is valid UTF-8 by construction.
        f.write_str(core::str::from_utf8(&text).map_err(|_| fmt::Error)?)
    }
}

impl FromStr for Ulid {
    type Err = DecodeError;

    fn from_str(text: &str) -> Result<Self, DecodeError> {
        let bytes = text.as_bytes();
        if bytes.len() != ULID_LEN {
            return Err(DecodeError::InvalidLength);
        }

        let mut value: u128 = 0;
        for &byte in bytes {
            let digit = LOOKUP[usize::from(byte)];
            if digit == NO_VALUE {
                return Err(DecodeError::InvalidChar);
            }
            value = (value << 5) | u128::from(digit);
        }
        Ok(Self(value))
    }
}

impl Serialize for Ulid {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.collect_str(self)
    }
}

impl<'de> Deserialize<'de> for Ulid {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let text = String::deserialize(deserializer)?;
        text.parse().map_err(serde::de::Error::custom)
    }
}

/// Why a string failed to parse as a ULID.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum DecodeError {
    /// Not exactly 26 bytes.
    InvalidLength,
    /// A byte outside the Crockford base32 alphabet.
    InvalidChar,
}

impl fmt::Display for DecodeError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidLength => f.write_str("invalid length"),
            Self::InvalidChar => f.write_str("invalid character"),
        }
    }
}

impl std::error::Error for DecodeError {}

#[cfg(test)]
mod tests {
    use proptest::prelude::*;

    use super::{DecodeError, Ulid};

    /// Produced by `ulid 1.2.1` before it was removed: the port must reproduce
    /// these exactly or every persisted id would re-render differently.
    const VECTORS: &[(u128, &str)] = &[
        (0, "00000000000000000000000000"),
        (1, "00000000000000000000000001"),
        (31, "0000000000000000000000000Z"),
        (32, "00000000000000000000000010"),
        (u128::MAX, "7ZZZZZZZZZZZZZZZZZZZZZZZZZ"),
        (
            0x0123_4567_89ab_cdef_0123_4567_89ab_cdef,
            "014D2PF2DBSQQG28T5CY4TQKFF",
        ),
        (1 << 80, "00000000010000000000000000"),
        ((1 << 127) | 0x3039, "40000000000000000000000C1S"),
        (
            0x019f_dc0a_07a6_d97a_af52_1124_930f_025c,
            "01KZE0M1X6V5XAYMGH4J9GY0JW",
        ),
        (
            0x0156_3e3a_b5d3_d676_4c61_efb9_9302_bd5b,
            "01ARZ3NDEKTSV4RRFFQ69G5FAV",
        ),
    ];

    #[test]
    fn matches_the_ulid_crate_vectors() {
        for &(value, text) in VECTORS {
            assert_eq!(Ulid(value).to_string(), text, "encode {value:#x}");
            assert_eq!(text.parse(), Ok(Ulid(value)), "decode {text}");
        }
    }

    /// A thousand values run through `ulid 1.2.1` itself (see
    /// `tests/fixtures/README.md`): encode, decode, and the timestamp split.
    #[test]
    fn matches_the_ulid_crate_on_a_thousand_generated_values() {
        const GOLDEN: &str = include_str!("../tests/fixtures/ulid_golden.tsv");
        let mut checked = 0;
        for line in GOLDEN
            .lines()
            .filter(|l| !l.is_empty() && !l.starts_with('#'))
        {
            let cols: Vec<&str> = line.split('\t').collect();
            assert_eq!(cols.len(), 3, "malformed fixture line {line:?}");
            let value = u128::from_str_radix(cols[0], 16).unwrap_or(0);
            let id = Ulid(value);
            assert_eq!(id.to_string(), cols[1], "encode {}", cols[0]);
            assert_eq!(cols[1].parse::<Ulid>(), Ok(id), "decode {}", cols[1]);
            assert_eq!(
                id.timestamp_ms().to_string(),
                cols[2],
                "timestamp of {}",
                cols[1]
            );
            checked += 1;
        }
        assert_eq!(checked, 1000, "the fixture must be intact");
    }

    #[test]
    fn splits_timestamp_and_random_like_the_crate() {
        let real: Ulid = "01KZE0M1X6V5XAYMGH4J9GY0JW".parse().unwrap_or(Ulid(0));
        assert_eq!(real.timestamp_ms(), 1_786_103_072_678);
        let spec: Ulid = "01ARZ3NDEKTSV4RRFFQ69G5FAV".parse().unwrap_or(Ulid(0));
        assert_eq!(spec.timestamp_ms(), 1_469_922_850_259);
        assert_eq!(Ulid(u128::MAX).timestamp_ms(), 281_474_976_710_655);

        let mixed = Ulid(0x0123_4567_89ab_cdef_0123_4567_89ab_cdef);
        assert_eq!(mixed.timestamp_ms(), 1_250_999_896_491);
        assert_eq!(mixed.random(), 0xcdef_0123_4567_89ab_cdef);
        assert_eq!(
            mixed.to_bytes(),
            [
                1, 35, 69, 103, 137, 171, 205, 239, 1, 35, 69, 103, 137, 171, 205, 239
            ]
        );
        assert_eq!(Ulid::from_bytes(mixed.to_bytes()), mixed);
    }

    #[test]
    fn from_parts_masks_overflow_like_the_crate() {
        let all_ones = Ulid::from_parts(u64::MAX, u128::MAX);
        assert_eq!(all_ones, Ulid(u128::MAX));
        assert_eq!(all_ones.to_string(), "7ZZZZZZZZZZZZZZZZZZZZZZZZZ");

        let spec = Ulid::from_parts(1_469_922_850_259, 0xdead_beef);
        assert_eq!(spec, Ulid(0x0156_3e3a_b5d3_0000_0000_0000_dead_beef));
        assert_eq!(spec.to_string(), "01ARZ3NDEK0000000003FAVFQF");
        assert_eq!(spec.timestamp_ms(), 1_469_922_850_259);
        assert_eq!(spec.random(), 0xdead_beef);
    }

    #[test]
    fn decodes_either_letter_case_and_drops_overflow_like_the_crate() {
        let lower: Result<Ulid, _> = "01kze0m1x6v5xaymgh4j9gy0jw".parse();
        assert_eq!(lower, Ok(Ulid(0x019f_dc0a_07a6_d97a_af52_1124_930f_025c)));
        // A leading `Z` carries 5 bits into a 3-bit slot; the crate shifted the
        // excess off the top and so do we.
        let upper: Result<Ulid, _> = "ZZZZZZZZZZZZZZZZZZZZZZZZZZ".parse();
        assert_eq!(upper, Ok(Ulid(u128::MAX)));
        let lower_z: Result<Ulid, _> = "zzzzzzzzzzzzzzzzzzzzzzzzzz".parse();
        assert_eq!(lower_z, Ok(Ulid(u128::MAX)));
    }

    #[test]
    fn rejects_bad_length_and_bad_characters() {
        for text in [
            "",
            "0",
            "01KZE0M1X6V5XAYMGH4J9GY0J",
            "01KZE0M1X6V5XAYMGH4J9GY0JWW",
        ] {
            assert_eq!(
                text.parse::<Ulid>(),
                Err(DecodeError::InvalidLength),
                "{text:?}"
            );
        }
        // `U` is not in the Crockford alphabet (nor are `I`, `L`, `O`).
        for text in ["01KZE0M1X6V5XAYMGH4J9GY0JU", "01KZE0M1X6V5XAYMGH4J9GY0J-"] {
            assert_eq!(
                text.parse::<Ulid>(),
                Err(DecodeError::InvalidChar),
                "{text:?}"
            );
        }
        assert_eq!(
            Ulid::from_string("01KZE0M1X6V5XAYMGH4J9GY0JW").map(|u| u.0),
            Ok(0x019f_dc0a_07a6_d97a_af52_1124_930f_025c)
        );
    }

    #[test]
    fn serde_uses_the_canonical_string_form() {
        let json = serde_json::to_string(&Ulid(0x0123_4567_89ab_cdef_0123_4567_89ab_cdef)).ok();
        assert_eq!(json.as_deref(), Some("\"014D2PF2DBSQQG28T5CY4TQKFF\""));
        let back: Option<Ulid> = serde_json::from_str("\"01KZE0M1X6V5XAYMGH4J9GY0JW\"").ok();
        assert_eq!(back, Some(Ulid(0x019f_dc0a_07a6_d97a_af52_1124_930f_025c)));
        assert!(serde_json::from_str::<Ulid>("\"nope\"").is_err());
    }

    #[test]
    fn debug_shows_the_payload_like_the_crate() {
        assert_eq!(format!("{:?}", Ulid(5)), "Ulid(5)");
    }

    #[test]
    fn new_stamps_now_and_draws_fresh_randomness() {
        let before = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map_or(0, |d| u64::try_from(d.as_millis()).unwrap_or(u64::MAX));
        let a = Ulid::new();
        let b = Ulid::new();
        let after = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map_or(u64::MAX, |d| {
                u64::try_from(d.as_millis()).unwrap_or(u64::MAX)
            });

        assert!(
            (before..=after).contains(&a.timestamp_ms()),
            "{a} stamped within the call"
        );
        assert!(
            a.timestamp_ms() <= b.timestamp_ms(),
            "later id never stamps earlier"
        );
        assert_ne!(a.random(), b.random(), "two draws share no random part");
        assert_ne!(a.random(), 0);
    }

    proptest! {
        #[test]
        fn text_and_bytes_round_trip(value in any::<u128>()) {
            let id = Ulid(value);
            let text = id.to_string();
            prop_assert_eq!(text.len(), 26);
            prop_assert_eq!(text.parse::<Ulid>(), Ok(id));
            prop_assert_eq!(text.to_lowercase().parse::<Ulid>(), Ok(id));
            prop_assert_eq!(Ulid::from_bytes(id.to_bytes()), id);
            prop_assert_eq!(Ulid::from_parts(id.timestamp_ms(), id.random()), id);
        }

        /// The property the store relies on for `ver_` keys and note ids: text
        /// order IS numeric order, so a listing sorted by key is sorted by time.
        #[test]
        fn text_order_matches_numeric_order(a in any::<u128>(), b in any::<u128>()) {
            let (ta, tb) = (Ulid(a).to_string(), Ulid(b).to_string());
            prop_assert_eq!(a.cmp(&b), ta.cmp(&tb));
            prop_assert_eq!(Ulid(a).cmp(&Ulid(b)), a.cmp(&b));
        }
    }
}
