//! The `hippius-mem mint-token` subcommand (gated behind the `console` feature).
//!
//! Mints an S3 sub-token from api.hippius.com for the mnemonic in
//! `HIPPIUS_MEM_MNEMONIC` and writes the `{access_key_id, secret}` pair to a
//! `0600` TOML fragment the operator can merge into `hippius-mem.toml`. The
//! secret is never printed to stdout/stderr or logged: only the public
//! `access_key_id` and the output path are reported via `tracing`.

use std::io::Write;

use anyhow::{Context, bail};
use hippius_mem_core::{ConsoleClient, DEFAULT_CONSOLE_BASE_URL, S3Creds};

/// Default file the minted credentials are written to.
const DEFAULT_OUT_PATH: &str = "./hippius-mem-subtoken.toml";
/// Default sub-token label when `--name` is omitted.
const DEFAULT_TOKEN_NAME: &str = "hippius-mem";

/// Run the `mint-token` subcommand over the args following `mint-token`.
///
/// # Errors
///
/// Returns an error if `--bucket` is missing, `HIPPIUS_MEM_MNEMONIC` is unset,
/// the mint flow fails, or the credentials file cannot be written.
pub(crate) async fn run(args: &[String]) -> anyhow::Result<()> {
    let opts = Options::parse(args)?;
    let mnemonic = std::env::var("HIPPIUS_MEM_MNEMONIC")
        .context("set HIPPIUS_MEM_MNEMONIC to the team mnemonic before minting a sub-token")?;
    let base_url = std::env::var("HIPPIUS_MEM_CONSOLE_URL")
        .unwrap_or_else(|_| DEFAULT_CONSOLE_BASE_URL.to_owned());

    let client = ConsoleClient::new(base_url);
    let creds = client
        .mint_sub_token(&mnemonic, &opts.bucket, &opts.name)
        .await?;

    write_secret_file(&opts.out, &creds)
        .with_context(|| format!("writing credentials to {}", opts.out))?;

    // The access_key_id is public; the secret only ever reaches the 0600 file.
    tracing::info!(
        access_key_id = %creds.access_key_id,
        out = %opts.out,
        "minted S3 sub-token; secret written to a 0600 file — keep it private and never commit it"
    );
    Ok(())
}

/// Parsed `mint-token` arguments.
struct Options {
    /// Team bucket the sub-token is scoped to.
    bucket: String,
    /// Human-facing sub-token label.
    name: String,
    /// File the credentials are written to.
    out: String,
}

impl Options {
    /// Parse `--bucket <name> [--name <label>] [--out <path>]`.
    fn parse(args: &[String]) -> anyhow::Result<Self> {
        let mut bucket = None;
        let mut name = None;
        let mut out = None;
        let mut iter = args.iter();
        while let Some(arg) = iter.next() {
            match arg.as_str() {
                "--bucket" => bucket = Some(next_value(&mut iter, "--bucket")?),
                "--name" => name = Some(next_value(&mut iter, "--name")?),
                "--out" => out = Some(next_value(&mut iter, "--out")?),
                other => bail!(
                    "unknown mint-token argument `{other}`; usage: \
                     mint-token --bucket <name> [--name <label>] [--out <path>]"
                ),
            }
        }
        Ok(Self {
            bucket: bucket.context("mint-token requires --bucket <name>")?,
            name: name.unwrap_or_else(|| DEFAULT_TOKEN_NAME.to_owned()),
            out: out.unwrap_or_else(|| DEFAULT_OUT_PATH.to_owned()),
        })
    }
}

/// Take the next argument as a flag value, or error naming the flag.
fn next_value<'a>(
    iter: &mut impl Iterator<Item = &'a String>,
    flag: &str,
) -> anyhow::Result<String> {
    iter.next()
        .map(ToOwned::to_owned)
        .with_context(|| format!("{flag} requires a value"))
}

/// Write the credentials as a TOML fragment to a freshly created `0600` file.
fn write_secret_file(path: &str, creds: &S3Creds) -> anyhow::Result<()> {
    let body = format!(
        "# Generated by `hippius-mem mint-token`. Merge into hippius-mem.toml.\n\
         # Contains a secret — keep it private (mode 0600) and never commit it.\n\
         access_key_id = \"{}\"\n\
         secret = \"{}\"\n",
        creds.access_key_id, creds.secret
    );
    let mut file = open_private(path)?;
    file.write_all(body.as_bytes())?;
    Ok(())
}

/// Open `path` for writing, creating it owner-read/write only (`0600`) so the
/// secret is not world-readable.
#[cfg(unix)]
fn open_private(path: &str) -> std::io::Result<std::fs::File> {
    use std::os::unix::fs::OpenOptionsExt;
    std::fs::OpenOptions::new()
        .write(true)
        .create(true)
        .truncate(true)
        .mode(0o600)
        .open(path)
}

/// Non-Unix fallback: create the file without a Unix permission mode.
#[cfg(not(unix))]
fn open_private(path: &str) -> std::io::Result<std::fs::File> {
    std::fs::OpenOptions::new()
        .write(true)
        .create(true)
        .truncate(true)
        .open(path)
}
